### ISSUE TITLE
Join forces with eslint-plugin-regexp

### ISSUE THREAD

**Issue by EvgenyOrekhov** [RunDevelopment/eslint-plugin-clean-regex#28]
## Description

Thanks for your great work on this plugin!

I was using [eslint-plugin-regexp](https://github.com/ota-meshi/eslint-plugin-regexp) for a while, and now I stumbled upon eslint-plugin-clean-regex. I can see that many rules are very similar in these two plugins.

@RunDevelopment and @ota-meshi, how do you feel about joining forces with each other by merging eslint-plugin-regexp and eslint-plugin-clean-regex into a single project?

**Comment by ota-meshi** [comment]
@EvgenyOrekhov Thank you for posting this.

Thank you to @RunDevelopment for posting the issue to eslint-plugin-regexp.
I would be grateful if I could continue to cooperate with @RunDevelopment!

> @RunDevelopment and @ota-meshi, how do you feel about joining forces with each other by merging eslint-plugin-regexp and eslint-plugin-clean-regex into a single project?

I think it would be great if it could be merging eslint-plugin-regexp and eslint-plugin-clean-regex.
As far as I can see, eslint-plugin-clean-regex is great because it analyzes regular expressions in detail. For example, eslint-plugin-regexp does not check the contents of Unicode properties, but eslint-plugin-clean-regex does. eslint-plugin-regexp also has some types of rules that eslint-plugin-clean-regex doesn't have. For example, a rule that verifies how it is used in a script, such as [regexp/no-unused-capturing-group](https://ota-meshi.github.io/eslint-plugin-regexp/rules/no-unused-capturing-group.html) rule.

However, the migration needs to be considered in depth.
I don't think you should force users to do a lot of migration work to merge projects.

I started making eslint-plugin-regexp to check the regex I wrote, but thankfully eslint-plugin-regexp now has some users. I'm particularly pleased that it's used in my favorite project core-js.

(I'm sorry I use broken English because I don't understand English)

**Comment by RunDevelopment** [comment]
I'm sorry for my late response @ota-meshi, @EvgenyOrekhov.

First of all, thank you @ota-meshi for considering collaborating with me. I too think that merging the projects would be beneficial. Yesterday, I tried out your `eslint-plugin-regexp` and was very impressed.

I made `eslint-plugin-clean-regex` to find mistakes in the over 2500 regexes of [PrismJS](https://github.com/PrismJS/prism). This is why this plugin only analyses regexes but not how they are used.

I would love to collaborate with you @ota-meshi. `eslint-plugin-regexp` already has a lot of awesome rule but I think that I could add a few more. :)

> However, the migration needs to be considered in depth.

Frankly, I consider archiving and deprecating `eslint-plugin-clean-regex` (after migration to `eslint-plugin-regexp` is possible). 

`eslint-plugin-regexp` looks to be technically superior (e.g. the [awesome docs](https://ota-meshi.github.io/eslint-plugin-regexp/), [the tooling](https://github.com/ota-meshi/eslint-plugin-regexp/tree/master/tools)). I also think that `eslint-plugin-regexp` is a better name. Should one project die as a result of use joining forces, it ought to be `eslint-plugin-clean-regex` IMO.

If we move all rules from `eslint-plugin-clean-regex` to `eslint-plugin-regexp`, then the migration won't be too difficult. I plan to write a small migration tool that "converts" the ESLint config for `eslint-plugin-clean-regex` rules (+options) to `eslint-plugin-regexp` rules. I will then publish one last version of `eslint-plugin-clean-regex` with the migration tool. Users can then simply run the migration tool.

**Comment by ota-meshi** [comment]
@RunDevelopment Thank you for considering the collaboration!!

I just wanted to let you know that I've added you as a maintainer on GitHub and npm.
Let me know if there is something missing.

> Frankly, I consider archiving and deprecating eslint-plugin-clean-regex (after migration to eslint-plugin-regexp is possible).

If it's okay for eslint-plugin-clean-regex users, I think your plan is great for me and eslint-plugin-regexp.

I am glad to collaborate with you!!

**Comment by RunDevelopment** [comment]
> I've added you as a maintainer on GitHub and npm.

Thank you @ota-meshi!

Over the next few days, I will read through the code of `eslint-plugin-regexp` and then move over issues and rules from `eslint-plugin-clean-regex`. You will get to review all changes/additions to the code base of course.

If you have any questions/suggestions/objections, feel free to tell me!

> If it's okay for eslint-plugin-clean-regex users

Users of `eslint-plugin-clean-regex` will get access to a linter that is better than `eslint-plugin-clean-regex`, so I think it's okay. The only downside will be migration efforts but the migration tool should mostly take care of that.

In the meantime, I will add a notice that new users should install `eslint-plugin-regexp` instead as this project is soon to be deprecated.
